# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
    
    - name: Restore dependencies
      run: dotnet restore -r linux-x64
      
    - name: Build
      run: |
        dotnet build --no-restore \
                     -c Release \
                     -r linux-x64
      
    - name: Publish
      run: |
        dotnet publish --no-restore \
                       --no-build \
                       -c Release \
                       -o publish \
                       -r linux-x64 \
                       -p:PublishAot=true \
                       -p:DebugType=None \
                       -p:DebugSymbols=false \
                       -p:AssemblyName='httpserver.linux-x64' \
                       HttpServer/HttpServer.csproj

